name: WGCustomFlags
main: com.mewin.WGCustomFlags.WGCustomFlagsPlugin
description: API for Bukkit plugin writers that allows you to add custom flags to WorldGuard regions.
version: 1.4

authors: [ mewin ]
depend: [ WorldGuard ]
softdepend: [ WorldEdit ]
website: http://dev.bukkit.org/server-mods/worldguard-custom-flags/
